### PR TITLE
Dotenv

### PR DESCRIPTION
**Pull request by dahadaller**
I added a more robust gitignore and added dotenv as a dependency. Changed a line in maps so that the tokens work out-of-the-box with a correct .env file (no more copy pasting)

### CODE REVIEW

**Comment by dahadaller** [comment]
Screenshot_2019-11-05 React App

**Comment by dahadaller** [comment]
Couldn't figure out where to initialize twit in the react code...so no tweets coming in yet

**Comment by smfils1** [comment]
@dahadaller are you using twit.get or twit.stream?

**Comment by Hongzred** [comment]
When merging your changes, I also added routing to the application and added unit testing file for twitterFeed component and added template

**Pull request merged**
